name: HawkScan
on:
  repository_dispatch:
    types: [integration-initial-test]
jobs:
  stackhawk-hawkscan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stackhawk/hawkscan-action@v1.3.4
      with:
        apiKey: ${{ secrets.hawk.qNsKNu3F7ErVUhLVFqVE.NddZYji1fNaC7SB68yq4 }}
        environmentVariables: APP_HOST APP_ENV
      env:
        APP_HOST: http://localhost:9000
        APP_ENV: Development
